include: ../analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: error
    include_file_not_found: ignore
linter:
  rules:
    public_member_api_docs: false
