name: flutter_hooks_gallery
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
    path: ../
  shared_preferences: ^0.4.3
  built_value: ^6.0.0
  built_collection: '>=2.0.0 <5.0.0'
  provider: 3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  built_value_generator: ^6.0.0
  build_runner: ^1.0.0

flutter:
  uses-material-design: true
