blank_issues_enabled: false
contact_links:
  - name: I have a problem and I need help
    url: https://github.com/rrousselGit/flutter_hooks/discussions
    about: Please ask and answer questions here.
